#!/bin/sh
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  cat "/home/jose/Repositories/cmake_toolbox/build_check/examples/gcov_test/mock_gcovr/mock_gcovr_help.txt"
  exit 0
fi
if [ "$1" = "--version" ]; then
  echo "gcovr 9.0"
  exit 0
fi
exit 0
