# SPDX-License-Identifier: MIT

#[=======================================================================[.rst:
CompileCommands
---------------

CMake module for manipulating compile_commands.json files.

This module provides functions to process and filter compile_commands.json
files generated by CMake.

Dependencies
^^^^^^^^^^^^

This module optionally uses jq for JSON processing. If jq is not available,
some functions will emit warnings.

Functions
^^^^^^^^^

.. command:: CompileCommands_Trim

  Trim/filter a compile_commands.json file::

    CompileCommands_Trim(
      INPUT <input_file>
      OUTPUT <output_file>
    )

  ``INPUT``
    Path to the source compile_commands.json file.

  ``OUTPUT``
    Path where the trimmed output will be written.

  This function creates a custom command that filters the compile_commands.json
  file using a jq script.

Example
^^^^^^^

.. code-block:: cmake

  include(CompileCommands)
  
  CompileCommands_Trim(
    INPUT ${CMAKE_BINARY_DIR}/compile_commands.json
    OUTPUT ${CMAKE_BINARY_DIR}/trimmed_compile_commands.json
  )

#]=======================================================================]

include_guard(GLOBAL)

# ==============================================================================
# Find jq (optional)
# ==============================================================================

find_package(Jq QUIET)

# ==============================================================================
# CompileCommands_Trim
# ==============================================================================
#
# Trim/filter a compile_commands.json file.
#
# Parameters:
#   INPUT  - Path to source compile_commands.json
#   OUTPUT - Path for output file
#
function(CompileCommands_Trim)
    set(options "")
    set(oneValueArgs INPUT OUTPUT)
    set(multiValueArgs "")
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_INPUT)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: INPUT must be specified")
    endif()

    if(NOT ARG_OUTPUT)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: OUTPUT must be specified")
    endif()

    if(NOT Jq_FOUND)
        message(WARNING "${CMAKE_CURRENT_FUNCTION}: jq not found, cannot trim compile commands")
        return()
    endif()

    set(JQ_SCRIPT
        ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/prune_compile_commands/prune_compile_commands.jq
    )

    set(HELPER_SCRIPT
        ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/internal/TrimCompileCommandsHelper.cmake
    )

    cmake_path(GET ARG_OUTPUT PARENT_PATH output_dir)
    file(MAKE_DIRECTORY ${output_dir})

    add_custom_command(
        OUTPUT ${ARG_OUTPUT}
        COMMAND
            ${CMAKE_COMMAND} -P ${HELPER_SCRIPT}
            -DJQ_EXECUTABLE=${Jq_EXECUTABLE}
            -DINPUT_FILE=${ARG_INPUT}
            -DOUTPUT_FILE=${ARG_OUTPUT}
            -DJQ_SCRIPT=${JQ_SCRIPT}
        DEPENDS
            ${ARG_INPUT}
            ${JQ_SCRIPT}
            ${HELPER_SCRIPT}
        COMMENT "Trimming compile commands: ${ARG_INPUT} -> ${ARG_OUTPUT}"
    )
endfunction()

# ==============================================================================
# Backward Compatibility Alias
# ==============================================================================

function(compile_commands_trim)
    message(DEPRECATION "compile_commands_trim() is deprecated, use CompileCommands_Trim() instead")
    CompileCommands_Trim(${ARGN})
endfunction()
