# SPDX-License-Identifier: MIT

#[=======================================================================[.rst:
CompileCommands
---------------

CMake module for manipulating compile_commands.json files.

This module provides functions to process and filter compile_commands.json
files generated by CMake.

Dependencies
^^^^^^^^^^^^

This module uses built-in CMake JSON processing to trim compile commands.

Functions
^^^^^^^^^

.. command:: CompileCommands_Trim

  Trim/filter a compile_commands.json file::

    CompileCommands_Trim(
      INPUT <input_file>
      OUTPUT <output_file>
    )

  ``INPUT``
    Path to the source compile_commands.json file.

  ``OUTPUT``
    Path where the trimmed output will be written.

  This function creates a custom command that filters the compile_commands.json
  file using a CMake helper script.

Example
^^^^^^^

.. code-block:: cmake

  include(CompileCommands)
  
  CompileCommands_Trim(
    INPUT ${CMAKE_BINARY_DIR}/compile_commands.json
    OUTPUT ${CMAKE_BINARY_DIR}/trimmed_compile_commands.json
  )

#]=======================================================================]

include_guard(GLOBAL)

set(COMPILECOMMANDS_AVAILABLE TRUE CACHE INTERNAL "Whether CompileCommands module is available")

get_property(_compilecommands_multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if(_compilecommands_multi_config)
    set(COMPILECOMMANDS_AVAILABLE
        FALSE
        CACHE INTERNAL
        "Whether CompileCommands module is available"
        FORCE
    )
    message(
        WARNING
        "CompileCommands: Multi-config generators do not produce compile_commands.json. "
        "Module disabled."
    )

    function(CompileCommands_Trim)
        message(
            WARNING
            "${CMAKE_CURRENT_FUNCTION}: compile_commands.json is unavailable with multi-config generators"
        )
    endfunction()
    unset(_compilecommands_multi_config)
    return()
endif()
unset(_compilecommands_multi_config)

# ==============================================================================
# CompileCommands_Trim
# ==============================================================================
#
# Trim/filter a compile_commands.json file.
#
# Parameters:
#   INPUT  - Path to source compile_commands.json
#   OUTPUT - Path for output file
#
function(CompileCommands_Trim)
    set(options "")
    set(oneValueArgs
        INPUT
        OUTPUT
    )
    set(multiValueArgs "")
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_INPUT)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: INPUT must be specified")
    endif()

    if(NOT ARG_OUTPUT)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: OUTPUT must be specified")
    endif()

    set(HELPER_SCRIPT ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/internal/TrimCompileCommandsHelper.cmake)

    cmake_path(GET ARG_OUTPUT PARENT_PATH output_dir)
    file(MAKE_DIRECTORY "${output_dir}")

    add_custom_command(
        OUTPUT
            ${ARG_OUTPUT}
        COMMAND
            ${CMAKE_COMMAND} -DINPUT_FILE=${ARG_INPUT} -DOUTPUT_FILE=${ARG_OUTPUT} -P
            ${HELPER_SCRIPT}
        DEPENDS
            ${ARG_INPUT}
            ${HELPER_SCRIPT}
        COMMENT "Trimming compile commands: ${ARG_INPUT} -> ${ARG_OUTPUT}"
        VERBATIM
    )
endfunction()
