# SPDX-License-Identifier: MIT

#[=======================================================================[.rst:
DiscoverTests
-------------

CMake script for discovering Unity tests from a test executable.

This script is intended to be run with ``cmake -P`` to extract individual
test names from a Unity test executable and generate CTest add_test() calls.

Usage
^^^^^

This script is called by the Ceedling module and is not intended for direct use.
It requires the following variables to be defined:

``TEST_EXECUTABLE``
  Path to the test executable to query.

``TEST_WORKING_DIR``
  Working directory for running the test executable.

``TEST_SUITE``
  Name of the test suite (usually the executable name).

``TEST_FILE``
  Path where the generated CTest script will be written.

Internal Function
^^^^^^^^^^^^^^^^^

.. command:: DiscoverTests_Generate

  Run a Unity test executable with ``-l`` flag to list tests,
  then generate a CMake script with add_test() calls::

    DiscoverTests_Generate(
      TEST_EXECUTABLE <path>
      TEST_WORKING_DIR <directory>
      TEST_SUITE <name>
      TEST_FILE <output_file>
    )

#]=======================================================================]

# ==============================================================================
# DiscoverTests_Generate
# ==============================================================================
#
# Generate CTest add_test() calls from a Unity test executable.
#
function(DiscoverTests_Generate)
    set(options "")
    set(oneValueArgs
        TEST_EXECUTABLE
        TEST_WORKING_DIR
        TEST_SUITE
        TEST_FILE
    )
    set(multiValueArgs "")
    cmake_parse_arguments(PARSE_ARGV 0 ARG "${options}" "${oneValueArgs}" "${multiValueArgs}")

    # Validate required arguments
    if(NOT ARG_TEST_EXECUTABLE)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: TEST_EXECUTABLE must be specified")
    endif()
    if(NOT ARG_TEST_SUITE)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: TEST_SUITE must be specified")
    endif()
    if(NOT ARG_TEST_FILE)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: TEST_FILE must be specified")
    endif()

    # Run the executable with -l flag to list tests
    cmake_language(
        EVAL CODE
            "execute_process(
                COMMAND ${ARG_TEST_EXECUTABLE} -l
                WORKING_DIRECTORY [==[${ARG_TEST_WORKING_DIR}]==]
                OUTPUT_VARIABLE output
                RESULT_VARIABLE result
            )"
    )

    if(NOT ${result} EQUAL 0)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: Failed to get tests from '${ARG_TEST_EXECUTABLE}'")
    endif()

    # Convert output to list (each line is a test name)
    string(REPLACE "\n" ";" output "${output}")

    # The first entry/line is always the test executable name, skip it
    list(REMOVE_AT output 0)

    # Generate add_test() calls for each test
    set(script "# Auto-generated by DiscoverTests.cmake\n")
    foreach(line ${output})
        string(STRIP "${line}" test_name)
        if(test_name)
            string(APPEND script
                "add_test(\"${ARG_TEST_SUITE}/${test_name}\" ${ARG_TEST_SUITE} -f ${test_name})\n"
            )
        endif()
    endforeach()

    # Write the generated script to disk
    file(WRITE "${ARG_TEST_FILE}" "${script}")
endfunction()

# ==============================================================================
# Script Mode Entry Point
# ==============================================================================
#
# When called with cmake -P, execute the function with provided variables.
#
if(CMAKE_SCRIPT_MODE_FILE)
    DiscoverTests_Generate(
        TEST_EXECUTABLE ${TEST_EXECUTABLE}
        TEST_WORKING_DIR ${TEST_WORKING_DIR}
        TEST_SUITE ${TEST_SUITE}
        TEST_FILE ${TEST_FILE}
    )
endif()
