# ==============================================================================
# PUBLIC API FUNCTIONS
# ==============================================================================

function(policy_register)
    set(options)
    set(oneValueArgs NAME DESCRIPTION DEFAULT INTRODUCED_VERSION WARNING DEPRECATED_VERSION REMOVED_VERSION)
    set(multiValueArgs)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_NAME)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires NAME <policy_name>")
    endif()
    if(NOT ARG_DESCRIPTION)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires DESCRIPTION <description>")
    endif()
    if(NOT ARG_DEFAULT)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires DEFAULT <NEW|OLD>")
    endif()
    if(NOT ARG_INTRODUCED_VERSION)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires INTRODUCED_VERSION <version>")
    endif()

    # WARNING is optional, default to empty string
    if(NOT ARG_WARNING)
        set(ARG_WARNING "")
    endif()
    
    # DEPRECATED_VERSION and REMOVED_VERSION are optional
    if(NOT ARG_DEPRECATED_VERSION)
        set(ARG_DEPRECATED_VERSION "")
    endif()
    if(NOT ARG_REMOVED_VERSION)
        set(ARG_REMOVED_VERSION "")
    endif()

    # Escape pipe characters in warning message to avoid conflicts with field separator
    string(REPLACE "|" "\\|" _escaped_warning "${ARG_WARNING}")

    _policy_check_newold("${ARG_DEFAULT}")
    _policy_registry_get(_policy_registry)
    foreach(_entry ${_policy_registry})
        if(NOT _entry STREQUAL "")
            string(REPLACE ";" "|" __sep_check "${_entry}")
            string(REPLACE ";" ";" _fields "${_entry}") # legacy, not needed
            separate_arguments(_fields UNIX_COMMAND "${_entry}")
            list(GET _fields 0 _existing)
            if(_existing STREQUAL "${ARG_NAME}")
                message(FATAL_ERROR "POLICY: Already registered: ${ARG_NAME}")
            endif()
        endif()
    endforeach()
    _policy_registry_append("'${ARG_NAME}'|'${ARG_DESCRIPTION}'|'${ARG_DEFAULT}'|'${ARG_INTRODUCED_VERSION}'|'${_escaped_warning}'|'${ARG_DEPRECATED_VERSION}'|'${ARG_REMOVED_VERSION}'")
endfunction()

function(policy_set)
    set(options)
    set(oneValueArgs POLICY VALUE)
    set(multiValueArgs)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_POLICY)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires POLICY <policy_name>")
    endif()
    if(NOT ARG_VALUE)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires VALUE <NEW|OLD>")
    endif()

    _policy_find("${ARG_POLICY}" _idx)
    if(_idx LESS 0)
        message(FATAL_ERROR "POLICY: ${ARG_POLICY} not registered")
    endif()
    _policy_check_newold("${ARG_VALUE}")
    _policy_write("${ARG_POLICY}" "${ARG_VALUE}")
    
    # Clear warning flags since the policy state has changed
    # This allows appropriate warnings to be shown again if accessed
    set_property(GLOBAL PROPERTY POLICY_WARNED_CURRENT_${ARG_POLICY} FALSE)
    set_property(GLOBAL PROPERTY POLICY_WARNED_DEPRECATED_UNSET_${ARG_POLICY} FALSE)
    set_property(GLOBAL PROPERTY POLICY_WARNED_DEPRECATED_SET_${ARG_POLICY} FALSE)
    # Note: REMOVED warnings are not cleared as they should always warn once regardless
endfunction()

function(policy_get)
    set(options)
    set(oneValueArgs POLICY OUTVAR)
    set(multiValueArgs)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_POLICY)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires POLICY <policy_name>")
    endif()
    if(NOT ARG_OUTVAR)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires OUTVAR <output_variable>")
    endif()

    _policy_find("${ARG_POLICY}" _idx)
    if(_idx LESS 0)
        message(FATAL_ERROR "POLICY: ${ARG_POLICY} not registered")
    endif()
    
    # Check policy status and print warnings before getting value
    _policy_check_and_warn("${ARG_POLICY}")
    
    _policy_registry_get(_policy_registry)
    list(GET _policy_registry ${_idx} _entry)
    if("${_entry}" STREQUAL "")
        message(FATAL_ERROR "POLICY: Registry is corrupted or empty for ${ARG_POLICY}")
    endif()
    _policy_record_unpack("${_entry}" _fields)
    if(NOT _fields)
        message(FATAL_ERROR "POLICY: Policy entry malformed for ${ARG_POLICY}: ${_entry}")
    endif()
    list(LENGTH _fields _field_len)
    if(_field_len LESS 3)
        message(FATAL_ERROR "POLICY: Policy registry entry too short for ${ARG_POLICY} (fields: ${_fields})")
    endif()
    list(GET _fields 2 _def)
    _policy_read(${ARG_POLICY} _val)
    if(NOT _val STREQUAL "")
        _policy_check_newold("${_val}")
        set(${ARG_OUTVAR} "${_val}" PARENT_SCOPE)
    else()
        message(NOTICE "POLICY: '${ARG_POLICY}' not set, using default: ${_def}")
        set(${ARG_OUTVAR} "${_def}" PARENT_SCOPE)
    endif()
endfunction()

function(policy_version)
    set(options)
    set(oneValueArgs MINIMUM MAXIMUM)
    set(multiValueArgs)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_MINIMUM)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires MINIMUM <min_version> (usage: MINIMUM <ver> [MAXIMUM <ver>])")
    endif()

    set(min_version "${ARG_MINIMUM}")
    set(do_max 0)
    if(ARG_MAXIMUM)
        set(max_version "${ARG_MAXIMUM}")
        set(do_max 1)
    endif()

    _policy_registry_get(_policy_registry)
    foreach(_entry ${_policy_registry})
        if(NOT _entry STREQUAL "")
            _policy_record_unpack("${_entry}" _fields)
            list(LENGTH _fields _field_len)
            if(_field_len LESS 4)
                message(FATAL_ERROR "POLICY: Registry entry too short (fields: ${_fields})")
            endif()
            list(GET _fields 0 pname)
            list(GET _fields 3 introver)
            _policy_version_compare_gte("${min_version}" "${introver}" _gte)
            if(_gte)
                policy_set(POLICY "${pname}" VALUE NEW)
            endif()
            if(do_max)
                _policy_version_compare_gte("${introver}" "${max_version}" _overmax)
                if(_overmax)
                    policy_set(POLICY "${pname}" VALUE OLD)
                endif()
            endif()
        endif()
    endforeach()
endfunction()

function(policy_info)
    set(options)
    set(oneValueArgs POLICY)
    set(multiValueArgs)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_POLICY)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires POLICY <policy_name>")
    endif()

    _policy_find("${ARG_POLICY}" _idx)
    if(_idx LESS 0)
        message(FATAL_ERROR "POLICY: ${ARG_POLICY} not registered")
    endif()
    _policy_registry_get(_policy_registry)
    list(GET _policy_registry ${_idx} _entry)
    if("${_entry}" STREQUAL "")
        message(FATAL_ERROR "POLICY: Registry is corrupted or empty for ${ARG_POLICY}")
    endif()
    _policy_record_unpack("${_entry}" _fields)
    if(NOT _fields)
        message(FATAL_ERROR "POLICY: Policy entry malformed for ${ARG_POLICY}: ${_entry}")
    endif()
    list(LENGTH _fields _field_len)
    if(_field_len LESS 4)
        message(FATAL_ERROR "POLICY: Policy registry entry too short for ${ARG_POLICY} (fields: ${_fields})")
    endif()
    
    list(GET _fields 0 _name)
    list(GET _fields 1 _desc)
    list(GET _fields 2 _default)
    list(GET _fields 3 _version)
    
    # Get optional fields
    set(_warning "")
    set(_deprecated_ver "")
    set(_removed_ver "")
    
    if(_field_len GREATER 4)
        list(GET _fields 4 _warning)
    endif()
    if(_field_len GREATER 5)
        list(GET _fields 5 _deprecated_ver)
    endif()
    if(_field_len GREATER 6)
        list(GET _fields 6 _removed_ver)
    endif()
    
    # Get current value
    _policy_read("${ARG_POLICY}" _current_value)
    if(_current_value STREQUAL "")
        set(_current_value "${_default} (default)")
    endif()
    
    message(STATUS "Policy Information for ${ARG_POLICY}:")
    message(STATUS "  Description: ${_desc}")
    message(STATUS "  Default: ${_default}")
    message(STATUS "  Introduced in version: ${_version}")
    message(STATUS "  Current value: ${_current_value}")
    
    if(NOT _deprecated_ver STREQUAL "")
        message(STATUS "  Deprecated in version: ${_deprecated_ver}")
    endif()
    if(NOT _removed_ver STREQUAL "")
        message(STATUS "  Removed in version: ${_removed_ver}")
    endif()
    if(NOT _warning STREQUAL "")
        message(STATUS "  Warning: ${_warning}")
    endif()
endfunction()

function(policy_get_fields)
    set(options)
    set(oneValueArgs POLICY PREFIX)
    set(multiValueArgs)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_POLICY)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires POLICY <policy_name>")
    endif()
    if(NOT ARG_PREFIX)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: requires PREFIX <variable_prefix>")
    endif()

    _policy_find("${ARG_POLICY}" _idx)
    if(_idx LESS 0)
        message(FATAL_ERROR "POLICY: ${ARG_POLICY} not registered")
    endif()
    _policy_registry_get(_policy_registry)
    list(GET _policy_registry ${_idx} _entry)
    if("${_entry}" STREQUAL "")
        message(FATAL_ERROR "POLICY: Registry is corrupted or empty for ${ARG_POLICY}")
    endif()
    _policy_record_unpack("${_entry}" _fields)
    if(NOT _fields)
        message(FATAL_ERROR "POLICY: Policy entry malformed for ${ARG_POLICY}: ${_entry}")
    endif()
    list(LENGTH _fields _field_len)
    if(_field_len LESS 4)
        message(FATAL_ERROR "POLICY: Policy registry entry too short for ${ARG_POLICY} (fields: ${_fields})")
    endif()
    
    # Set the basic fields
    list(GET _fields 0 _name)
    list(GET _fields 1 _desc)
    list(GET _fields 2 _default)
    list(GET _fields 3 _version)
    
    set(${ARG_PREFIX}_NAME "${_name}" PARENT_SCOPE)
    set(${ARG_PREFIX}_DESCRIPTION "${_desc}" PARENT_SCOPE)
    set(${ARG_PREFIX}_DEFAULT "${_default}" PARENT_SCOPE)
    set(${ARG_PREFIX}_INTRODUCED_VERSION "${_version}" PARENT_SCOPE)
    
    # Set optional fields
    if(_field_len GREATER 4)
        list(GET _fields 4 _warning)
        set(${ARG_PREFIX}_WARNING "${_warning}" PARENT_SCOPE)
    else()
        set(${ARG_PREFIX}_WARNING "" PARENT_SCOPE)
    endif()
    
    if(_field_len GREATER 5)
        list(GET _fields 5 _deprecated_ver)
        set(${ARG_PREFIX}_DEPRECATED_VERSION "${_deprecated_ver}" PARENT_SCOPE)
    else()
        set(${ARG_PREFIX}_DEPRECATED_VERSION "" PARENT_SCOPE)
    endif()
    
    if(_field_len GREATER 6)
        list(GET _fields 6 _removed_ver)
        set(${ARG_PREFIX}_REMOVED_VERSION "${_removed_ver}" PARENT_SCOPE)
    else()
        set(${ARG_PREFIX}_REMOVED_VERSION "" PARENT_SCOPE)
    endif()
    
    # Get and set current value
    _policy_read("${ARG_POLICY}" _current_value)
    if(_current_value STREQUAL "")
        set(${ARG_PREFIX}_CURRENT_VALUE "${_default}" PARENT_SCOPE)
        set(${ARG_PREFIX}_IS_DEFAULT TRUE PARENT_SCOPE)
    else()
        set(${ARG_PREFIX}_CURRENT_VALUE "${_current_value}" PARENT_SCOPE)
        set(${ARG_PREFIX}_IS_DEFAULT FALSE PARENT_SCOPE)
    endif()
endfunction()

# ==============================================================================
# PRIVATE HELPER FUNCTIONS
# ==============================================================================

function(_policy_check_newold VALUE)
    if(NOT "${VALUE}" STREQUAL "NEW" AND NOT "${VALUE}" STREQUAL "OLD")
        message(FATAL_ERROR "POLICY: Value must be NEW or OLD (got '${VALUE}').")
    endif()
endfunction()

function(_policy_read POLICY OUTVAR)
    get_property(_policy GLOBAL PROPERTY POLICY_${POLICY})
    set(${OUTVAR} "${_policy}" PARENT_SCOPE)
endfunction()

function(_policy_write POLICY VALUE)
    set_property(GLOBAL PROPERTY PROPERTY POLICY_${POLICY} "${VALUE}")
endfunction()

function(_policy_registry_write REGISTRY)
    set_property(GLOBAL PROPERTY POLICY_REGISTRY "${REGISTRY}")
endfunction()

function(_policy_registry_get OUTVAR)
    get_property(_registry GLOBAL PROPERTY POLICY_REGISTRY)
    set(${OUTVAR} "${_registry}" PARENT_SCOPE)
endfunction()

function(_policy_registry_append RECORD)
    _policy_registry_get(_policy_registry)
    list(APPEND _policy_registry "${RECORD}")
    _policy_registry_write("${_policy_registry}")
endfunction()

function(_policy_record_unpack RECORD OUTVAR)
    # First, temporarily replace escaped pipes with a placeholder
    string(REPLACE "\\|" "___ESCAPED_PIPE___" RECORD "${RECORD}")
    # Then split on pipes to get fields
    string(REPLACE "|" ";" _fields "${RECORD}")
    # Restore escaped pipes and strip quotes from each field
    set(_restored_fields "")
    foreach(_field ${_fields})
        string(REPLACE "___ESCAPED_PIPE___" "|" _field "${_field}")
        # Strip leading and trailing single quotes
        string(REPLACE "'" "" _field "${_field}")
        list(APPEND _restored_fields "${_field}")
    endforeach()
    set(${OUTVAR} "${_restored_fields}" PARENT_SCOPE)
endfunction()

function(_policy_find POLICY_NAME OUTINDEX)
    set(_found -1)
    set(_i 0)
    _policy_registry_get(_policy_registry)
    foreach(_entry ${_policy_registry})
        if(NOT _entry STREQUAL "")
            _policy_record_unpack("${_entry}" _fields)
            list(GET _fields 0 _key)
            if(_key STREQUAL "${POLICY_NAME}")
                set(_found ${_i})
                break()
            endif()
        endif()
        math(EXPR _i "${_i} + 1")
    endforeach()
    set(${OUTINDEX} ${_found} PARENT_SCOPE)
endfunction()

function(_policy_version_compare_gte v1 v2 OUT)
    string(REPLACE "." ";" _v1list "${v1}")
    string(REPLACE "." ";" _v2list "${v2}")
    list(LENGTH _v1list _v1len)
    list(LENGTH _v2list _v2len)
    if(_v1len LESS 3)
        math(EXPR _diff "3 - ${_v1len}")
        foreach(_i RANGE 1 ${_diff})
            list(APPEND _v1list "0")
        endforeach()
    endif()
    if(_v2len LESS 3)
        math(EXPR _diff "3 - ${_v2len}")
        foreach(_i RANGE 1 ${_diff})
            list(APPEND _v2list "0")
        endforeach()
    endif()

    list(GET _v1list 0 _v1maj)
    list(GET _v2list 0 _v2maj)
    list(GET _v1list 1 _v1min)
    list(GET _v2list 1 _v2min)
    list(GET _v1list 2 _v1pat)
    list(GET _v2list 2 _v2pat)

    if(_v1maj GREATER _v2maj)
        set(${OUT} 1 PARENT_SCOPE)
        return()
    elseif(_v1maj LESS _v2maj)
        set(${OUT} 0 PARENT_SCOPE)
        return()
    endif()
    if(_v1min GREATER _v2min)
        set(${OUT} 1 PARENT_SCOPE)
        return()
    elseif(_v1min LESS _v2min)
        set(${OUT} 0 PARENT_SCOPE)
        return()
    endif()
    if(_v1pat GREATER_EQUAL _v2pat)
        set(${OUT} 1 PARENT_SCOPE)
    else()
        set(${OUT} 0 PARENT_SCOPE)
    endif()
endfunction()

function(_policy_check_and_warn POLICY_NAME)
    _policy_find("${POLICY_NAME}" _idx)
    if(_idx LESS 0)
        return() # Policy not found, caller will handle error
    endif()
    
    _policy_registry_get(_policy_registry)
    list(GET _policy_registry ${_idx} _entry)
    _policy_record_unpack("${_entry}" _fields)
    list(LENGTH _fields _field_len)
    
    if(_field_len LESS 4)
        return() # Malformed entry, caller will handle error
    endif()
    
    # Get policy information
    list(GET _fields 0 _name)
    list(GET _fields 1 _desc)
    list(GET _fields 2 _default)
    list(GET _fields 3 _introduced_ver)
    
    # Get optional fields
    set(_warning "")
    set(_deprecated_ver "")
    set(_removed_ver "")
    
    if(_field_len GREATER 4)
        list(GET _fields 4 _warning)
    endif()
    if(_field_len GREATER 5)
        list(GET _fields 5 _deprecated_ver)
    endif()
    if(_field_len GREATER 6)
        list(GET _fields 6 _removed_ver)
    endif()
    
    # Check if policy is explicitly set
    _policy_read("${POLICY_NAME}" _current_value)
    set(_is_explicitly_set FALSE)
    if(NOT _current_value STREQUAL "")
        set(_is_explicitly_set TRUE)
    endif()
    
    # Determine warning type and check if we've already warned about this specific scenario
    set(_warning_key "")
    set(_should_warn FALSE)
    
    # Check policy status and determine appropriate warning
    # Priority: REMOVED > DEPRECATED > REGULAR WARNING
    if(NOT _removed_ver STREQUAL "")
        # Policy is removed - always warn regardless of whether it's set
        set(_warning_key "POLICY_WARNED_REMOVED_${POLICY_NAME}")
        get_property(_already_warned GLOBAL PROPERTY ${_warning_key})
        if(NOT _already_warned)
            message(AUTHOR_WARNING "Policy ${POLICY_NAME} was removed in version ${_removed_ver}. "
                    "This policy is no longer supported and should not be used.")
            set(_should_warn TRUE)
        endif()
    elseif(NOT _deprecated_ver STREQUAL "")
        # Policy is deprecated - different warning based on whether it's set
        if(NOT _is_explicitly_set)
            set(_warning_key "POLICY_WARNED_DEPRECATED_UNSET_${POLICY_NAME}")
            get_property(_already_warned GLOBAL PROPERTY ${_warning_key})
            if(NOT _already_warned)
                message(AUTHOR_WARNING "Policy ${POLICY_NAME} is deprecated since version ${_deprecated_ver}. "
                        "Please set this policy explicitly using cmake_policy(SET ${POLICY_NAME} NEW) or cmake_policy(SET ${POLICY_NAME} OLD). "
                        "This policy will be removed in a future version.")
                set(_should_warn TRUE)
            endif()
        else()
            set(_warning_key "POLICY_WARNED_DEPRECATED_SET_${POLICY_NAME}")
            get_property(_already_warned GLOBAL PROPERTY ${_warning_key})
            if(NOT _already_warned)
                message(AUTHOR_WARNING "Policy ${POLICY_NAME} is deprecated since version ${_deprecated_ver} "
                        "and will be removed in a future version.")
                set(_should_warn TRUE)
            endif()
        endif()
    else()
        # Policy is current - print warning only if not explicitly set and has a warning
        if(NOT _is_explicitly_set AND NOT _warning STREQUAL "")
            set(_warning_key "POLICY_WARNED_CURRENT_${POLICY_NAME}")
            get_property(_already_warned GLOBAL PROPERTY ${_warning_key})
            if(NOT _already_warned)
                message(AUTHOR_WARNING "Policy ${POLICY_NAME}: ${_warning} "
                        "Please set this policy explicitly using cmake_policy(SET ${POLICY_NAME} NEW) or cmake_policy(SET ${POLICY_NAME} OLD).")
                set(_should_warn TRUE)
            endif()
        endif()
    endif()
    
    # Mark this specific warning scenario as shown
    if(_should_warn AND NOT _warning_key STREQUAL "")
        set_property(GLOBAL PROPERTY ${_warning_key} TRUE)
    endif()
endfunction()

